# Generated by Django 4.1 on 2022-11-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_friend_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='img'),
        ),
    ]
