# Generated by Django 4.1 on 2022-11-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_friend_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='img',
        ),
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='img'),
        ),
    ]
